### ISSUE TITLE
Setting for 'record only new episodes' is inverted

### ISSUE THREAD

**Issue by parkingzone** [babgvant/Emby.MythTv#11]
Series view (http://192.168.1.10:8096/web/livetvseriestimers.html), series detail has 'record only new episodes' unchecked when it is defined in MythTV. And vice versa.

In other words, the check box in the plugin is indicating the opposite of the check box in the correlating Mythtv schedule definition.

**Comment by babgvant** [comment]
Thanks. Will be fixed in next release.
