### ISSUE TITLE
Live TV recordings and deleted recordings are being displayed

### ISSUE THREAD

**Issue by parkingzone** [babgvant/Emby.MythTv#3]
Live TV recordings (generated while watching live TV using MythTV) and deleted recordings show under "Latest Recordings" and "All Recordings" sections within the Emby clients.

I personally would prefer that these types of recordings are not shown. It would be nice to have the types of recordings to be omitted/shown as a setting within the plugin.

My guess would be that most people would not want to see live or deleted recordings.

**Comment by babgvant** [comment]
Can you provide the XML from http://yourserverip:6544/Dvr/GetRecordedList and highlight the items you would like to be removed?

**Comment by parkingzone** [comment]
I identified the XML variable.

```
<ProgramList>
  <Programs>
    <Program>
      <Recording>
        <RecGroup>VALUE</RecGroup>
      </Recording>
    </Program>
  </Programs>
</ProgramList>
```

The VALUE is "Deleted" for deleted recordings and "LiveTV" for live TV recordings.

These values were set by MythTV. Otherwise, the recording group value is shown as defined by the MythTV user.

**Comment by babgvant** [comment]
Should be fixed via a setting that lets you add the values ("Deleted", "LiveTV" are defaults) in latest release (same URL).

**Comment by parkingzone** [comment]
Initial testing omitted "Deleted" recordings but not "LiveTV" recordings. I edited the default value to exclude the space character and then both recording groups where omitted.

Default plugin setting of "Deleted, LiveTV" changed to "Deleted,LiveTV" was successful.

I discovered that restarting the Emby server is required for changes to the MythTV plugin to be recognized.

Emby Server Version: 3.0.5675.1
Emby MythTV Plugin Version: 1.0.5722.38984

**Comment by babgvant** [comment]
Typo on my part, thanks. I will remove leading/trailing spaces when building the list too. 

You don't have to restart, but you do need to make it refresh the guide/channels/recordings lists. Restarting is the easiest way to do that (there are tasks for some of these things as well).
